### ISSUE TITLE
Solana address is't the same as rewards account

### ISSUE THREAD

**Issue by wenweih** [0xrsydn/ore-miner#2]
Hi, the Solana address (obtain via `solana-keygen pubkey`) is not the same as miner account, may I know does it  correct or not?

I am encountering the error when run rewards command: 
```
Failed to get miner account: Error { request: None, kind: RpcError(ForUser("AccountNotFound: pubkey={pubkey_a}")) }
```
pubkey_a is not the same as generated Solana address.

this guy report the same issue on ore-cli repo -> https://github.com/HardhatChad/ore-cli/issues/20

Thank you.

**Comment by 0xrsydn** [comment]
Yeah i think many people get this same issue where the generated wallet and our miner account (ore-cli) have different pubkey (mismatched) so it failed to get miner. I dont know how is that happen, but im assuming its from ore-cli itself(?). Just checked the issue, the only way for now is just to permarun claim command for now till it hit the right one.

Also you may import your private key to phantom/solflare to see if your pubkey is the right one as the generated wallet in the first place i think? If the imported address is sames as pubkey we generated, i assume its from ore-cli itself (need to be solved)

**Comment by Tuukster** [comment]
'solana address' returns B6aT4y2TgnRY4E9961E46aGvDptiP4zRKTNbnfqb3ejU but when I imported it to Phantom it gives me 3vUmnP2mG7WuapaYSMk1WXB8AAikayKht3skeL9q6jRL. Also, rewards command returns 7fTW5ApNXmxFHvpLZhnEhcVFcSp2Ruv8JVXEy34zpCwn.

A bit confused. Is this working as intended? Other story is that I have not landed a single transaction. Been trying all day with priority 10000001 🤕

**Comment by 0xrsydn** [comment]
> 'solana address' returns B6aT4y2TgnRY4E9961E46aGvDptiP4zRKTNbnfqb3ejU but when I imported it to Phantom it gives me 3vUmnP2mG7WuapaYSMk1WXB8AAikayKht3skeL9q6jRL. Also, rewards command returns 7fTW5ApNXmxFHvpLZhnEhcVFcSp2Ruv8JVXEy34zpCwn.
> 
> A bit confused. Is this working as intended? Other story is that I have not landed a single transaction. Been trying all day with priority 10000001 🤕

For importing your address to phantom, did you using seed phrase or private key? I suggest you import it using private key instead of seed phrase because i was having same issue before with seed phrase, after i try to import it through private key, it has same address.
```
cd ~/.config/solana/
ls
```
You should see your id.json (your private key) located there. For different address in ore miner account i can't really help since i think its from ore-cli issue

**Comment by Tuukster** [comment]
Thanks! That private key trick solved this first address mismatch :)

**Comment by Tuukster** [comment]
The rewards address fixed itself once I had something to claim

**Comment by wenweih** [comment]
@Tuukster yup, me as well.

By the way, do you have any idea how to setup the configure for increasing possibility to mine the tokens? I've been running the service for a few days now, but haven't received any rewards

**Comment by 0xrsydn** [comment]
> @Tuukster yup, me as well.
> 
> By the way, do you have any idea how to setup the configure for increasing possibility to mined the tokens? I've been running the service for a few days now, but haven't received any rewards

try running lot of terminals with different rpcs i think (for now..)

**Comment by wenweih** [comment]
ok, thanks @0xrsydn @Tuukster 

So far, the different pubkey issue is solved

Thank you so much.
