### ISSUE TITLE
./target/release/ore: No such file or directory

### ISSUE THREAD

**Issue by Svertem** [0xrsydn/ore-miner#3]
![image](https://github.com/0xrsydn/ore-miner/assets/65705890/d5eeef14-6850-4745-a0f3-87f4b005bdcd)
can you help?

**Comment by 0xrsydn** [comment]
```
cd ./target/release/
ls
```
make sure there is `ore` on the list since it says the file doesnt exist, if it doesnt exist i might suggest you to reinstall ore-cli through cargo again. Also i think i complicated the script little bit. Try change the command to:
```
COMMAND="ore --rpc ${RPC_URL} --keypair ${KEY} --priority-fee ${FEE} mine --threads ${THREADS}"
```
if its still doesnt work, i think its better to reinstall ore-cli
